### PR TITLE
Full SegWit support & bug fixes

### PR DESCRIPTION
**Pull request by losh11**
This is an extremely simple PR to support. A single line change in `loafwallet-ios`.

in `loafwallet-ios/breadwallet/src/BRCore.swift#382`:
```
// from this
BRTransactionAddInput(self, txHash, index, amount, script, script.count, signature, signature?.count ?? 0, sequence)
// to
BRTransactionAddInput(self, txHash, index, amount, script, script.count, signature, signature?.count ?? 0, [], 0, sequence)
```

This includes all bug fixes made to all witness related changes by BRD over a 1 year period after deployment to public. Also contains various minor peer changes.

### CODE REVIEW

**Review by kcw-grunt — CHANGES_REQUESTED** [review]
Thanks @losh11  but this is not needed for iOS at this time. No users are asking for it and we have a **very serious** need for bech32 support for Android.

Can you change base this to:

https://github.com/litecoin-foundation/loafwallet-core (master)

And reference notes in : https://github.com/litecoin-foundation/loafwallet-android/issues/179 ?

**Comment by losh11** [comment]
Is there any reason why this can’t be merged into the iOS app only? I think
it’s absolutely untrue that no user is interested in an update that reduces
fees by half & reduces blockchain bloat.

**Comment by kcw-grunt** [comment]
@losh11 to answer your question, the implementation of bech32 is different for each platform and our marketing efforts are better supported by having similar level of bech32 compliance.  Once Android can accept bech32 to the same degree that iOS , we will move both platforms together to get more broad usage and messaging.

**Comment by kcw-grunt** [comment]
Closing this in favor os creating a new issue.

**Pull request merged**
