### PR TITLE
make sure to call balanceChanged callback whenever balance is updated

### PR DESCRIPTION
**Pull request by mosadialiou**
This PR fixes this issue https://github.com/litecoin-foundation/loafwallet-android/issues/117

### CODE REVIEW

**Comment by mosadialiou** [comment]
@kcw-grunt Don't have privilege to add reviewers. Could you fix that please. BTW add @losh11 here

**Review by losh11 — APPROVED** [review]
utACK. LGTM, although untested.

**Comment by mosadialiou** [comment]
@losh11 Thanks! So what do you need to test the changes in order to merge the PR?

**Comment by losh11** [comment]
Both the reviewers and the PR author should test these changes. Will try to test ASAP. Also waiting on @kcw-grunt.

**Review by kcw-grunt — APPROVED** [review]
lgtm

**Comment by mosadialiou** [comment]
Yeah sure. 
On my side I already did the necessary tests.

**Review by kcw-grunt — CHANGES_REQUESTED** [review]
want to setup the branching first for iOS and Android. (Small work but it needs to be done)

**Comment by kcw-grunt** [comment]
> utACK. LGTM, although untested.

@losh11 I need admin access to this repo to organize the branching accordingly...

**Comment by losh11** [comment]
Okay done. Although please use GitHub's approval button to approve this PR. Request changes should only be used if there's a specific issue with the PR. Set up branch protection rules requiring that admins review PR before they can be merged.

**Comment by mosadialiou** [comment]
Let me know if you want me to share my test variables in order to sync faster. With that the sync starts from Dec 16, 2019

**Review by kcw-grunt — APPROVED** [review]
ramping up...lgtm

**Pull request merged**
