### PR TITLE
🚀[Release v1.0.0] Merge into Main 

### PR DESCRIPTION
**Pull request by kcw-grunt**
# Hero merge
- Adds fpRate (False Positive Rate)
- Accepts fpRate for the BloomFilter to modulate the sync time for the user
- User can balance privacy vs sync time
- Last major update to the library

## Test Process

- [ ] Update the git submodule for `litewallet-android`
- [ ] Verify litewallet-ios is **not** adversely unaffected
- [ ] Update the git submodule for `litewallet-ios`
- [ ] Verify litewallet-ios is **not** adversely unaffected

### CODE REVIEW

**Review by josikie — APPROVED** [review]
Nice! Both changes on BRPeerManager.c and BRPeerManager.h. What is bloomFilter used for?

**Comment by kcw-grunt** [comment]
Wow...thanks so much for the look @josikie  
Really needed it. We are in panic mode.

The Bloom Filter in short is a way to send a bunch of **potential** addresses to a node so the node doesn't know which ones you care about.  The more false positives we send to the node the less likely the node knows which addresses are actually mine.

In the extreme, I can just send the node just **my addresses only** which means the random litecoin node can track what addresses are mine and it puts a spotlight on me.  So, there is no privacy for me as a Litewallet user.

What we are trying to do is let the Litewallet user make sync as quick as possible without telling every node "Hey look at all my addresses and all my Litecoin!" 

Make sense @josikie ?

**Comment by josikie** [comment]
Thank you for the answer! @kcw-grunt That's make sense. Are the potential addresses a fake address?

**Comment by kcw-grunt** [comment]
> Thank you for the answer! @kcw-grunt That's make sense. Are the potential addresses a fake address?
Well they are valid ltc addresses. The idea, @josikie , is  the node cannot distinguish between **your** address that you care about and other addresses

**Comment by josikie** [comment]
Oh that's good!  @kcw-grunt

**Pull request merged**
