### PR TITLE
🦺[Tech Debt] Revert secp256 lib to the prod/stable version

### PR DESCRIPTION
**Pull request by kcw-grunt**
# Why?

Per discussion with @losh11 we should not move/update/change the secp256k1 library as the latest Bitcore devs are building for taproot.  This is a breaking change

# What
Set to the correct commit: `b408c6a`

### CODE REVIEW

**Review by josikie — APPROVED** [review]
Waw 140 files, what is taproot?

**Comment by kcw-grunt** [comment]
> Waw 140 files, what is taproot?

It's a Bitcoin feature. Not very familiar with it but it we are always piggybacking off of Bitcoin as Litecoin is a fork so we always have to evaluate if bringing in upgrades helps or hurts.

In this case, it caused a major issue. Please standby as I will need to revert/ change this PR

**Comment by kcw-grunt** [comment]
Thanks for the  ✅ @josikie

**Comment by josikie** [comment]
Thanks too for the explanation 👍🏼 👍🏼  @kcw-grunt

**Pull request merged**
